backend:
  name: github
  repo: bluecroc7290/Shlok-Negi
  branch: main

media_folder: "blog/images"
public_folder: "/blog/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
